// International calling codes for the contact form's phone field.
// Belize pinned first as the default selection, everything else alphabetical by name.
export const COUNTRY_CODES = [
  { name: 'Belize', abbr: 'BZ', code: '+501' },
  { name: 'Afghanistan', abbr: 'AF', code: '+93' },
  { name: 'Albania', abbr: 'AL', code: '+355' },
  { name: 'Algeria', abbr: 'DZ', code: '+213' },
  { name: 'Andorra', abbr: 'AD', code: '+376' },
  { name: 'Angola', abbr: 'AO', code: '+244' },
  { name: 'Antigua and Barbuda', abbr: 'AG', code: '+1268' },
  { name: 'Argentina', abbr: 'AR', code: '+54' },
  { name: 'Armenia', abbr: 'AM', code: '+374' },
  { name: 'Australia', abbr: 'AU', code: '+61' },
  { name: 'Austria', abbr: 'AT', code: '+43' },
  { name: 'Azerbaijan', abbr: 'AZ', code: '+994' },
  { name: 'Bahamas', abbr: 'BS', code: '+1242' },
  { name: 'Bahrain', abbr: 'BH', code: '+973' },
  { name: 'Bangladesh', abbr: 'BD', code: '+880' },
  { name: 'Barbados', abbr: 'BB', code: '+1246' },
  { name: 'Belarus', abbr: 'BY', code: '+375' },
  { name: 'Belgium', abbr: 'BE', code: '+32' },
  { name: 'Benin', abbr: 'BJ', code: '+229' },
  { name: 'Bhutan', abbr: 'BT', code: '+975' },
  { name: 'Bolivia', abbr: 'BO', code: '+591' },
  { name: 'Bosnia and Herzegovina', abbr: 'BA', code: '+387' },
  { name: 'Botswana', abbr: 'BW', code: '+267' },
  { name: 'Brazil', abbr: 'BR', code: '+55' },
  { name: 'Brunei', abbr: 'BN', code: '+673' },
  { name: 'Bulgaria', abbr: 'BG', code: '+359' },
  { name: 'Burkina Faso', abbr: 'BF', code: '+226' },
  { name: 'Burundi', abbr: 'BI', code: '+257' },
  { name: 'Cambodia', abbr: 'KH', code: '+855' },
  { name: 'Cameroon', abbr: 'CM', code: '+237' },
  { name: 'Canada', abbr: 'CA', code: '+1' },
  { name: 'Cape Verde', abbr: 'CV', code: '+238' },
  { name: 'Central African Republic', abbr: 'CF', code: '+236' },
  { name: 'Chad', abbr: 'TD', code: '+235' },
  { name: 'Chile', abbr: 'CL', code: '+56' },
  { name: 'China', abbr: 'CN', code: '+86' },
  { name: 'Colombia', abbr: 'CO', code: '+57' },
  { name: 'Comoros', abbr: 'KM', code: '+269' },
  { name: 'Congo', abbr: 'CG', code: '+242' },
  { name: 'Costa Rica', abbr: 'CR', code: '+506' },
  { name: 'Croatia', abbr: 'HR', code: '+385' },
  { name: 'Cuba', abbr: 'CU', code: '+53' },
  { name: 'Cyprus', abbr: 'CY', code: '+357' },
  { name: 'Czech Republic', abbr: 'CZ', code: '+420' },
  { name: 'Democratic Republic of the Congo', abbr: 'CD', code: '+243' },
  { name: 'Denmark', abbr: 'DK', code: '+45' },
  { name: 'Djibouti', abbr: 'DJ', code: '+253' },
  { name: 'Dominica', abbr: 'DM', code: '+1767' },
  { name: 'Dominican Republic', abbr: 'DO', code: '+1809' },
  { name: 'East Timor', abbr: 'TL', code: '+670' },
  { name: 'Ecuador', abbr: 'EC', code: '+593' },
  { name: 'Egypt', abbr: 'EG', code: '+20' },
  { name: 'El Salvador', abbr: 'SV', code: '+503' },
  { name: 'Equatorial Guinea', abbr: 'GQ', code: '+240' },
  { name: 'Eritrea', abbr: 'ER', code: '+291' },
  { name: 'Estonia', abbr: 'EE', code: '+372' },
  { name: 'Eswatini', abbr: 'SZ', code: '+268' },
  { name: 'Ethiopia', abbr: 'ET', code: '+251' },
  { name: 'Fiji', abbr: 'FJ', code: '+679' },
  { name: 'Finland', abbr: 'FI', code: '+358' },
  { name: 'France', abbr: 'FR', code: '+33' },
  { name: 'Gabon', abbr: 'GA', code: '+241' },
  { name: 'Gambia', abbr: 'GM', code: '+220' },
  { name: 'Georgia', abbr: 'GE', code: '+995' },
  { name: 'Germany', abbr: 'DE', code: '+49' },
  { name: 'Ghana', abbr: 'GH', code: '+233' },
  { name: 'Greece', abbr: 'GR', code: '+30' },
  { name: 'Grenada', abbr: 'GD', code: '+1473' },
  { name: 'Guatemala', abbr: 'GT', code: '+502' },
  { name: 'Guinea', abbr: 'GN', code: '+224' },
  { name: 'Guinea-Bissau', abbr: 'GW', code: '+245' },
  { name: 'Guyana', abbr: 'GY', code: '+592' },
  { name: 'Haiti', abbr: 'HT', code: '+509' },
  { name: 'Honduras', abbr: 'HN', code: '+504' },
  { name: 'Hong Kong', abbr: 'HK', code: '+852' },
  { name: 'Hungary', abbr: 'HU', code: '+36' },
  { name: 'Iceland', abbr: 'IS', code: '+354' },
  { name: 'India', abbr: 'IN', code: '+91' },
  { name: 'Indonesia', abbr: 'ID', code: '+62' },
  { name: 'Iran', abbr: 'IR', code: '+98' },
  { name: 'Iraq', abbr: 'IQ', code: '+964' },
  { name: 'Ireland', abbr: 'IE', code: '+353' },
  { name: 'Israel', abbr: 'IL', code: '+972' },
  { name: 'Italy', abbr: 'IT', code: '+39' },
  { name: 'Ivory Coast', abbr: 'CI', code: '+225' },
  { name: 'Jamaica', abbr: 'JM', code: '+1876' },
  { name: 'Japan', abbr: 'JP', code: '+81' },
  { name: 'Jordan', abbr: 'JO', code: '+962' },
  { name: 'Kazakhstan', abbr: 'KZ', code: '+7' },
  { name: 'Kenya', abbr: 'KE', code: '+254' },
  { name: 'Kiribati', abbr: 'KI', code: '+686' },
  { name: 'Kosovo', abbr: 'XK', code: '+383' },
  { name: 'Kuwait', abbr: 'KW', code: '+965' },
  { name: 'Kyrgyzstan', abbr: 'KG', code: '+996' },
  { name: 'Laos', abbr: 'LA', code: '+856' },
  { name: 'Latvia', abbr: 'LV', code: '+371' },
  { name: 'Lebanon', abbr: 'LB', code: '+961' },
  { name: 'Lesotho', abbr: 'LS', code: '+266' },
  { name: 'Liberia', abbr: 'LR', code: '+231' },
  { name: 'Libya', abbr: 'LY', code: '+218' },
  { name: 'Liechtenstein', abbr: 'LI', code: '+423' },
  { name: 'Lithuania', abbr: 'LT', code: '+370' },
  { name: 'Luxembourg', abbr: 'LU', code: '+352' },
  { name: 'Macau', abbr: 'MO', code: '+853' },
  { name: 'Madagascar', abbr: 'MG', code: '+261' },
  { name: 'Malawi', abbr: 'MW', code: '+265' },
  { name: 'Malaysia', abbr: 'MY', code: '+60' },
  { name: 'Maldives', abbr: 'MV', code: '+960' },
  { name: 'Mali', abbr: 'ML', code: '+223' },
  { name: 'Malta', abbr: 'MT', code: '+356' },
  { name: 'Marshall Islands', abbr: 'MH', code: '+692' },
  { name: 'Mauritania', abbr: 'MR', code: '+222' },
  { name: 'Mauritius', abbr: 'MU', code: '+230' },
  { name: 'Mexico', abbr: 'MX', code: '+52' },
  { name: 'Micronesia', abbr: 'FM', code: '+691' },
  { name: 'Moldova', abbr: 'MD', code: '+373' },
  { name: 'Monaco', abbr: 'MC', code: '+377' },
  { name: 'Mongolia', abbr: 'MN', code: '+976' },
  { name: 'Montenegro', abbr: 'ME', code: '+382' },
  { name: 'Morocco', abbr: 'MA', code: '+212' },
  { name: 'Mozambique', abbr: 'MZ', code: '+258' },
  { name: 'Myanmar', abbr: 'MM', code: '+95' },
  { name: 'Namibia', abbr: 'NA', code: '+264' },
  { name: 'Nauru', abbr: 'NR', code: '+674' },
  { name: 'Nepal', abbr: 'NP', code: '+977' },
  { name: 'Netherlands', abbr: 'NL', code: '+31' },
  { name: 'New Zealand', abbr: 'NZ', code: '+64' },
  { name: 'Nicaragua', abbr: 'NI', code: '+505' },
  { name: 'Niger', abbr: 'NE', code: '+227' },
  { name: 'Nigeria', abbr: 'NG', code: '+234' },
  { name: 'North Korea', abbr: 'KP', code: '+850' },
  { name: 'North Macedonia', abbr: 'MK', code: '+389' },
  { name: 'Norway', abbr: 'NO', code: '+47' },
  { name: 'Oman', abbr: 'OM', code: '+968' },
  { name: 'Pakistan', abbr: 'PK', code: '+92' },
  { name: 'Palau', abbr: 'PW', code: '+680' },
  { name: 'Palestine', abbr: 'PS', code: '+970' },
  { name: 'Panama', abbr: 'PA', code: '+507' },
  { name: 'Papua New Guinea', abbr: 'PG', code: '+675' },
  { name: 'Paraguay', abbr: 'PY', code: '+595' },
  { name: 'Peru', abbr: 'PE', code: '+51' },
  { name: 'Philippines', abbr: 'PH', code: '+63' },
  { name: 'Poland', abbr: 'PL', code: '+48' },
  { name: 'Portugal', abbr: 'PT', code: '+351' },
  { name: 'Qatar', abbr: 'QA', code: '+974' },
  { name: 'Romania', abbr: 'RO', code: '+40' },
  { name: 'Russia', abbr: 'RU', code: '+7' },
  { name: 'Rwanda', abbr: 'RW', code: '+250' },
  { name: 'Saint Kitts and Nevis', abbr: 'KN', code: '+1869' },
  { name: 'Saint Lucia', abbr: 'LC', code: '+1758' },
  { name: 'Saint Vincent and the Grenadines', abbr: 'VC', code: '+1784' },
  { name: 'Samoa', abbr: 'WS', code: '+685' },
  { name: 'San Marino', abbr: 'SM', code: '+378' },
  { name: 'Sao Tome and Principe', abbr: 'ST', code: '+239' },
  { name: 'Saudi Arabia', abbr: 'SA', code: '+966' },
  { name: 'Senegal', abbr: 'SN', code: '+221' },
  { name: 'Serbia', abbr: 'RS', code: '+381' },
  { name: 'Seychelles', abbr: 'SC', code: '+248' },
  { name: 'Sierra Leone', abbr: 'SL', code: '+232' },
  { name: 'Singapore', abbr: 'SG', code: '+65' },
  { name: 'Slovakia', abbr: 'SK', code: '+421' },
  { name: 'Slovenia', abbr: 'SI', code: '+386' },
  { name: 'Solomon Islands', abbr: 'SB', code: '+677' },
  { name: 'Somalia', abbr: 'SO', code: '+252' },
  { name: 'South Africa', abbr: 'ZA', code: '+27' },
  { name: 'South Korea', abbr: 'KR', code: '+82' },
  { name: 'South Sudan', abbr: 'SS', code: '+211' },
  { name: 'Spain', abbr: 'ES', code: '+34' },
  { name: 'Sri Lanka', abbr: 'LK', code: '+94' },
  { name: 'Sudan', abbr: 'SD', code: '+249' },
  { name: 'Suriname', abbr: 'SR', code: '+597' },
  { name: 'Sweden', abbr: 'SE', code: '+46' },
  { name: 'Switzerland', abbr: 'CH', code: '+41' },
  { name: 'Syria', abbr: 'SY', code: '+963' },
  { name: 'Taiwan', abbr: 'TW', code: '+886' },
  { name: 'Tajikistan', abbr: 'TJ', code: '+992' },
  { name: 'Tanzania', abbr: 'TZ', code: '+255' },
  { name: 'Thailand', abbr: 'TH', code: '+66' },
  { name: 'Togo', abbr: 'TG', code: '+228' },
  { name: 'Tonga', abbr: 'TO', code: '+676' },
  { name: 'Trinidad and Tobago', abbr: 'TT', code: '+1868' },
  { name: 'Tunisia', abbr: 'TN', code: '+216' },
  { name: 'Turkey', abbr: 'TR', code: '+90' },
  { name: 'Turkmenistan', abbr: 'TM', code: '+993' },
  { name: 'Tuvalu', abbr: 'TV', code: '+688' },
  { name: 'Uganda', abbr: 'UG', code: '+256' },
  { name: 'Ukraine', abbr: 'UA', code: '+380' },
  { name: 'United Arab Emirates', abbr: 'AE', code: '+971' },
  { name: 'United Kingdom', abbr: 'GB', code: '+44' },
  { name: 'United States', abbr: 'US', code: '+1' },
  { name: 'Uruguay', abbr: 'UY', code: '+598' },
  { name: 'Uzbekistan', abbr: 'UZ', code: '+998' },
  { name: 'Vanuatu', abbr: 'VU', code: '+678' },
  { name: 'Vatican City', abbr: 'VA', code: '+379' },
  { name: 'Venezuela', abbr: 'VE', code: '+58' },
  { name: 'Vietnam', abbr: 'VN', code: '+84' },
  { name: 'Yemen', abbr: 'YE', code: '+967' },
  { name: 'Zambia', abbr: 'ZM', code: '+260' },
  { name: 'Zimbabwe', abbr: 'ZW', code: '+263' },
];
